# Generated by Django 4.0.1 on 2025-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnm', models.CharField(max_length=30)),
                ('eml', models.EmailField(max_length=254)),
                ('mob', models.IntegerField()),
                ('psw', models.CharField(max_length=20)),
                ('cpsw', models.CharField(max_length=20)),
            ],
        ),
    ]
